In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
df=pd.read_excel('/content/내국인_제주여행_방문지_20201028200517.xlsx')
df

   응답자수1 (명)  한라산 (%)  오름 (%)  성산일출봉 (%)  ...  제주바다체험장 (%)  골프장 (%)  카지노 (%)  기타 (%)
0       5558     16.5    21.4       39.3  ...          2.8        6      0.6    76.9

[1 rows x 62 columns]

In [ ]:
df.columns

Index(['응답자수1 (명)', '한라산 (%)', '오름 (%)', '성산일출봉 (%)', '섬(우도/마라도 등) (%)',
       '올레길 (%)', '폭포(정방폭포 등) (%)', '동굴(만장굴 등) (%)', '해수욕장 (%)', '비자림 (%)',
       '한라수목원 (%)', '서귀포자연휴양림 (%)', '절물자연휴양림 (%)', '용두암 (%)', '주상절리대 (%)',
       '한림공원 (%)', '응답자수2 (명)', '국립제주박물관 (%)', '도립미술관 (%)', '민속자연사박물관 (%)',
       '제주돌문화공원 (%)', '제주세계자연유산센터 (%)', '이중섭미술관 (%)', '서복전시관 (%)',
       '제주4.3평화공원 (%)', '응답자수3 (명)', '동문시장 (%)', '중앙로지하상가 (%)', '바오젠거리 (%)',
       '제주5일장(제주/서귀포) (%)', '서귀포매일올레시장 (%)', '신라면세점 (%)', '롯데면세점 (%)',
       '제주관광공사면세점 (%)', '공항면세점(JDC면세점) (%)', '응답자수4 (명)', '제주목관아 (%)',
       '항몽유적지 (%)', '성읍민속마을 (%)', '삼양동선사유적 (%)', '제주추사관 (%)', '관덕정 (%)',
       '이중섭거주지 (%)', '하멜기념비 (%)', '응답자수5 (명)', '미로공원(김녕/메이지 등) (%)',
       '에코랜드 (%)', '제주경마공원 (%)', '불교사찰 (%)', '아쿠아플라넷 (%)', '테디베어박물관 (%)',
       '소인국테마파크 (%)', '잠수함관광(서귀포 등) (%)', '신비의도로 (%)', '생각하는정원 (%)',
       '드라마촬영지 (%)', '제주별빛누리공원 (%)', '유람선(요트투어포함) (%)', '제주바다체험장 (%)',
       '골프장 (%)', '카지노 (%)', '기타 (%)'],
      dtype='object')

In [ ]:
col=[]
for i in df.columns:
  col.append(i[:i.find(' ')])

In [ ]:
col

['응답자수1',
 '한라산',
 '오름',
 '성산일출봉',
 '섬(우도/마라도',
 '올레길',
 '폭포(정방폭포',
 '동굴(만장굴',
 '해수욕장',
 '비자림',
 '한라수목원',
 '서귀포자연휴양림',
 '절물자연휴양림',
 '용두암',
 '주상절리대',
 '한림공원',
 '응답자수2',
 '국립제주박물관',
 '도립미술관',
 '민속자연사박물관',
 '제주돌문화공원',
 '제주세계자연유산센터',
 '이중섭미술관',
 '서복전시관',
 '제주4.3평화공원',
 '응답자수3',
 '동문시장',
 '중앙로지하상가',
 '바오젠거리',
 '제주5일장(제주/서귀포)',
 '서귀포매일올레시장',
 '신라면세점',
 '롯데면세점',
 '제주관광공사면세점',
 '공항면세점(JDC면세점)',
 '응답자수4',
 '제주목관아',
 '항몽유적지',
 '성읍민속마을',
 '삼양동선사유적',
 '제주추사관',
 '관덕정',
 '이중섭거주지',
 '하멜기념비',
 '응답자수5',
 '미로공원(김녕/메이지',
 '에코랜드',
 '제주경마공원',
 '불교사찰',
 '아쿠아플라넷',
 '테디베어박물관',
 '소인국테마파크',
 '잠수함관광(서귀포',
 '신비의도로',
 '생각하는정원',
 '드라마촬영지',
 '제주별빛누리공원',
 '유람선(요트투어포함)',
 '제주바다체험장',
 '골프장',
 '카지노',
 '기타']

In [ ]:
df.columns=col

In [ ]:
df

   응답자수1   한라산    오름  성산일출봉  섬(우도/마라도  ...  유람선(요트투어포함)  제주바다체험장  골프장  카지노    기타
0   5558  16.5  21.4   39.3      29.1  ...          6.5      2.8    6  0.6  76.9

[1 rows x 62 columns]

In [ ]:
df1=pd.DataFrame(df.iloc[0, 0:16])
df2=pd.DataFrame(df.iloc[0, 16:25])
df3=pd.DataFrame(df.iloc[0, 25:35])
df4=pd.DataFrame(df.iloc[0, 35:44])
df5=pd.DataFrame(df.iloc[0, 44:])

In [ ]:
df1=df1.transpose()
df2=df2.transpose()
df3=df3.transpose()
df4=df4.transpose()
df5=df5.transpose()

In [ ]:
df1

    응답자수1   한라산    오름  성산일출봉  섬(우도/마라도  ...  서귀포자연휴양림  절물자연휴양림   용두암  주상절리대  한림공원
0  5558.0  16.5  21.4   39.3      29.1  ...       6.3      7.6  25.6   19.1  11.3

[1 rows x 16 columns]

In [ ]:
df2

    응답자수2  국립제주박물관  도립미술관  민속자연사박물관  ...  제주세계자연유산센터  이중섭미술관  서복전시관  제주4.3평화공원
0  1237.0     16.7   10.1      23.4  ...         8.0    40.0    2.7       10.8

[1 rows x 9 columns]

In [ ]:
df3

    응답자수3  동문시장  중앙로지하상가  바오젠거리  ...  신라면세점  롯데면세점  제주관광공사면세점  공항면세점(JDC면세점)
0  4562.0  46.9      4.7    5.3  ...    2.3    4.4       16.0           43.6

[1 rows x 10 columns]

In [ ]:
df4

    응답자수4  제주목관아  항몽유적지  성읍민속마을  삼양동선사유적  제주추사관   관덕정  이중섭거주지  하멜기념비
0  1398.0    5.4    5.8    34.8      2.6    4.8  11.0    43.6   15.8

In [ ]:
df5

    응답자수5  미로공원(김녕/메이지  에코랜드  제주경마공원  ...  제주바다체험장  골프장  카지노    기타
0  3826.0         14.8  26.3     5.5  ...      2.8  6.0  0.6  76.9

[1 rows x 18 columns]

In [ ]:
df1.loc[0, ]

응답자수1       5558.0
한라산           16.5
오름            21.4
성산일출봉         39.3
섬(우도/마라도      29.1
올레길           25.9
폭포(정방폭포       26.9
동굴(만장굴        12.3
해수욕장          54.6
비자림           14.8
한라수목원          7.3
서귀포자연휴양림       6.3
절물자연휴양림        7.6
용두암           25.6
주상절리대         19.1
한림공원          11.3
Name: 0, dtype: float64

In [ ]:
list1=[5558]

In [ ]:
for i in list(df1.iloc[0, 1:]):
  list1.append(int(5558*(i/100)))

In [ ]:
list1

[5558,
 917,
 1189,
 2184,
 1617,
 1439,
 1495,
 683,
 3034,
 822,
 405,
 350,
 422,
 1422,
 1061,
 628]

In [ ]:
list2=[1237]
list3=[4562]
list4=[1398]
list5=[3826]

In [ ]:
for i in list(df2.iloc[0, 1:]):
  list2.append(int(1237*(i/100)))
for i in list(df3.iloc[0, 1:]):
  list3.append(int(4562*(i/100)))
for i in list(df4.iloc[0, 1:]):
  list4.append(int(1398*(i/100)))
for i in list(df5.iloc[0, 1:]):
  list5.append(int(3826*(i/100)))

In [ ]:
list1

[5558,
 917,
 1189,
 2184,
 1617,
 1439,
 1495,
 683,
 3034,
 822,
 405,
 350,
 422,
 1422,
 1061,
 628]

In [ ]:
list2

[1237, 206, 124, 289, 209, 98, 494, 33, 133]

In [ ]:
list3

[4562, 2139, 214, 241, 510, 1341, 104, 200, 729, 1989]

In [ ]:
list4

[1398, 75, 81, 486, 36, 67, 153, 609, 220]

In [ ]:
list5

[3826,
 566,
 1006,
 210,
 206,
 749,
 329,
 359,
 233,
 531,
 202,
 485,
 110,
 248,
 107,
 229,
 22,
 2942]

In [ ]:
listfinal=list1+list2+list3+list4+list5

In [ ]:
df

   응답자수1   한라산    오름  성산일출봉  섬(우도/마라도  ...  유람선(요트투어포함)  제주바다체험장  골프장  카지노    기타
0   5558  16.5  21.4   39.3      29.1  ...          6.5      2.8    6  0.6  76.9

[1 rows x 62 columns]

In [ ]:
df.loc[0]=listfinal

In [ ]:
df

   응답자수1    한라산      오름   성산일출봉  ...  제주바다체험장  골프장   카지노      기타
0   5558  917.0  1189.0  2184.0  ...    107.0  229  22.0  2942.0

[1 rows x 62 columns]

In [ ]:
df.drop(['응답자수1','응답자수2','응답자수3','응답자수4','응답자수5'],axis=1,inplace=True)

In [ ]:
df

     한라산      오름   성산일출봉  섬(우도/마라도  ...  제주바다체험장  골프장   카지노      기타
0  917.0  1189.0  2184.0    1617.0  ...    107.0  229  22.0  2942.0

[1 rows x 57 columns]

In [ ]:
df=df.transpose()

In [ ]:
df

                    0
한라산             917.0
오름             1189.0
성산일출봉          2184.0
섬(우도/마라도       1617.0
올레길            1439.0
폭포(정방폭포        1495.0
동굴(만장굴          683.0
해수욕장           3034.0
비자림             822.0
한라수목원           405.0
서귀포자연휴양림        350.0
절물자연휴양림         422.0
용두암            1422.0
주상절리대          1061.0
한림공원            628.0
국립제주박물관         206.0
도립미술관           124.0
민속자연사박물관        289.0
제주돌문화공원         209.0
제주세계자연유산센터       98.0
이중섭미술관          494.0
서복전시관            33.0
제주4.3평화공원       133.0
동문시장           2139.0
중앙로지하상가         214.0
바오젠거리           241.0
제주5일장(제주/서귀포)   510.0
서귀포매일올레시장      1341.0
신라면세점           104.0
롯데면세점           200.0
제주관광공사면세점       729.0
공항면세점(JDC면세점)  1989.0
제주목관아            75.0
항몽유적지            81.0
성읍민속마을          486.0
삼양동선사유적          36.0
제주추사관            67.0
관덕정             153.0
이중섭거주지          609.0
하멜기념비           220.0
미로공원(김녕/메이지     566.0
에코랜드           1006.0
제주경마공원          210.0
불교사찰            206.0
아쿠아플라넷          749.0
테디베어박물관         329.0
소인국테마파크         359.0
잠수함관광(서귀포       233.0
신비의도로           531.0
생각하는정원          202.0
드라마촬영지          485.0
제주별빛누리공원        110.0
유람선(요트투어포함)     248.0
제주바다체험장         107.0
골프장             229.0
카지노              22.0
기타             2942.0

In [ ]:
df.columns=['방문수']

In [ ]:
df

                  방문수
한라산             917.0
오름             1189.0
성산일출봉          2184.0
섬(우도/마라도       1617.0
올레길            1439.0
폭포(정방폭포        1495.0
동굴(만장굴          683.0
해수욕장           3034.0
비자림             822.0
한라수목원           405.0
서귀포자연휴양림        350.0
절물자연휴양림         422.0
용두암            1422.0
주상절리대          1061.0
한림공원            628.0
국립제주박물관         206.0
도립미술관           124.0
민속자연사박물관        289.0
제주돌문화공원         209.0
제주세계자연유산센터       98.0
이중섭미술관          494.0
서복전시관            33.0
제주4.3평화공원       133.0
동문시장           2139.0
중앙로지하상가         214.0
바오젠거리           241.0
제주5일장(제주/서귀포)   510.0
서귀포매일올레시장      1341.0
신라면세점           104.0
롯데면세점           200.0
제주관광공사면세점       729.0
공항면세점(JDC면세점)  1989.0
제주목관아            75.0
항몽유적지            81.0
성읍민속마을          486.0
삼양동선사유적          36.0
제주추사관            67.0
관덕정             153.0
이중섭거주지          609.0
하멜기념비           220.0
미로공원(김녕/메이지     566.0
에코랜드           1006.0
제주경마공원          210.0
불교사찰            206.0
아쿠아플라넷          749.0
테디베어박물관         329.0
소인국테마파크         359.0
잠수함관광(서귀포       233.0
신비의도로           531.0
생각하는정원          202.0
드라마촬영지          485.0
제주별빛누리공원        110.0
유람선(요트투어포함)     248.0
제주바다체험장         107.0
골프장             229.0
카지노              22.0
기타             2942.0

In [ ]:
df.drop('기타', axis=0, inplace=True)

In [ ]:
df['방문수']=df['방문수'].astype(int)

In [ ]:
df

                방문수
한라산             917
오름             1189
성산일출봉          2184
섬(우도/마라도       1617
올레길            1439
폭포(정방폭포        1495
동굴(만장굴          683
해수욕장           3034
비자림             822
한라수목원           405
서귀포자연휴양림        350
절물자연휴양림         422
용두암            1422
주상절리대          1061
한림공원            628
국립제주박물관         206
도립미술관           124
민속자연사박물관        289
제주돌문화공원         209
제주세계자연유산센터       98
이중섭미술관          494
서복전시관            33
제주4.3평화공원       133
동문시장           2139
중앙로지하상가         214
바오젠거리           241
제주5일장(제주/서귀포)   510
서귀포매일올레시장      1341
신라면세점           104
롯데면세점           200
제주관광공사면세점       729
공항면세점(JDC면세점)  1989
제주목관아            75
항몽유적지            81
성읍민속마을          486
삼양동선사유적          36
제주추사관            67
관덕정             153
이중섭거주지          609
하멜기념비           220
미로공원(김녕/메이지     566
에코랜드           1006
제주경마공원          210
불교사찰            206
아쿠아플라넷          749
테디베어박물관         329
소인국테마파크         359
잠수함관광(서귀포       233
신비의도로           531
생각하는정원          202
드라마촬영지          485
제주별빛누리공원        110
유람선(요트투어포함)     248
제주바다체험장         107
골프장             229
카지노              22